import { Link } from "react-router-dom";
export default function PhotAI() {
  return (
    <div className="text-lg px-10 lg:px-72 md:m-auto tracking-wider ">
      {" "}
      {/* Center text within this div */}
      <h1 className="font-semibold py-5 text-2xl">Phot.AI Example:</h1>
    
      <p>
        <span className="font-semibold">Step 1:</span> Upload image
      </p>
      <div>
        <img src="/phot.ai2.png" className="py-8" alt="Brandmark.io Logo"></img>
      </div>
      <p>
        <span className="font-semibold">Step 2:</span> Select Background to
        replace & enter new background in prompt (i.e., Beach)
      </p>
      <div>
        <img src="/phot.ai3.jpg" className="py-8" alt="Brandmark.io Logo"></img>
      </div>
      <p>
        <span className="font-semibold">Step 3:</span> Background is replaced
        with different images generated by AI
      </p>
      <div>
        <img src="/phot.ai4.jpg" className="py-8" alt="Brandmark.io Logo"></img>
      </div>
      <p>
        <span className="font-semibold">Step 4:</span> Final choice
      </p>
      <div>
        <img src="/phot.ai5.jpeg" className="py-8" alt="Brandmark.io Logo"></img>
      </div>

    </div>
  );
}
